### ISSUE TITLE
KeyError: 'AXO_API_KEY' when executing Retrieving Orders and Pool Data script

### ISSUE THREAD

**Issue by Rot-Front** [Charli3-Official/charli3-dendrite#105]
Running the Retrieving Orders and Pool Data script resulted in an error:
```
...\Lib\site-packages\pydantic\_internal\_fields.py:172: UserWarning: Field name "asset_mulitipliers" in "MinswapDJEDUSDCStableState" shadows an attribute in parent "MinswapDJEDiUSDStableState"
  warnings.warn(
Traceback (most recent call last):
  File "D:\Python\Project\winpyt312\Projects\Cardano\charl.py", line 7, in <module>
    from charli3_dendrite.backend import set_backend, get_backend
  File "D:\Python\Project\winpyt312\Lib\site-packages\charli3_dendrite\__init__.py", line 15, in <module>
    from charli3_dendrite.dexs.ob.axo import AxoOBMarketState
  File "D:\Python\Project\winpyt312\Lib\site-packages\charli3_dendrite\dexs\ob\axo.py", line 58, in <module>
    AXO_API_KEY = os.environ["AXO_API_KEY"]
                  ~~~~~~~~~~^^^^^^^^^^^^^^^
  File "<frozen os>", line 685, in __getitem__
KeyError: 'AXO_API_KEY'
```

**Comment by theeldermillenial** [comment]
Sorry that took so long. Fix on the way!
